Add rpm-no-comps fixture
pulp/pulp-fixtures pull request #251
Opened 2024-03-26 17:51 UTC by chris1984

2024-03-26 17:53 UTC, chris1984 commented
@ggainey here is my attempt at this no-comps.

2024-03-26 18:36 UTC, ggainey requested changes
Needs to have a separate [noissue] line in the commit-message as well.

2024-03-26 19:09 UTC, chris1984 commented on Makefile
> +fixtures/rpm-no-comps: fixtures
That makes sense, the part about me breaking the repo with removing the `comps.xml` and the `repomd.xml` still pointing to it. The only 2 repos I found that didn't have a `comps.xml` was `assets-modularity` and `assets-modular` Would manually creating an assets directory from `assets` then updating the `repomd.xml` to not have any reference to `comps.xml` then have the make file use that directory or is there a better way forward?

2024-03-26 20:04 UTC, ggainey commented on Makefile
> +fixtures/rpm-no-comps: fixtures
The general pattern is, in the build-stanza in the Makefile for your fixture, you `cp -r` from assets into your chosen dir-name, remove comps.xml, and then gen-fixture the resulting directory.

2024-03-28 14:46 UTC, chris1984 commented
@ggainey I think I got it figured out, looks right locally based on your feedback. Updated my commit message to have `[noissue]` inside it as well on a new line. Let me know how this looks?

2024-03-28 15:32 UTC, ggainey approved these changes
Looks good!

2024-03-28 15:32 UTC, merged